version: '3.1'

services:

  microservice:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
      - cache

  database:
    container_name: local_database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  cache:
    container_name: local_cache
    image: redis
    restart: always
    ports:
      - 6379:6379
networks:
  local-net:
    external: true